<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>14</LangVersion>
        <TargetFramework>net10.0-windows</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="OtterTex">
            <HintPath>..\Meddle.Utils\Lib\OtterTex.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Meddle.SqPack\Meddle.SqPack.csproj" />
    </ItemGroup>
</Project>
